### ISSUE TITLE
Can't not load ZIP file

### ISSUE THREAD

**Issue by jingweizhanggenzeon** [TBag/power-apps-copy-text-to-clipboard#9]
When uploading ZIP file, got this error message: 

Something went wrong. Please try again later

![image](https://user-images.githubusercontent.com/65175319/90643279-696fca00-e201-11ea-9357-19418792a5d3.png)

**Comment by OGcanviz** [comment]
@jingweizhanggenzeon This is a solution, so you should import it from the `Solutions` page.
